PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX fb: <http://rdf.freebase.com/ns/>

SELECT DISTINCT ?id ?value ?type WHERE {
  # Get additional information
  {
    VALUES ?id { {IDS} }
    ?id @en@fb:type.object.name ?value
    BIND("label" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id @en@fb:common.topic.alias ?value
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id @en@fb:common.topic.description ?value
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id fb:common.topic.notable_types ?typ_ .
    ?typ_ @en@fb:type.object.name ?typ
    BIND(CONCAT("has type ", ?typ) AS ?value)
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id fb:freebase.type_hints.mediator ?mediator
    FILTER(?mediator = "true")
    BIND("is compound value type / mediator type" AS ?value)
    BIND("info" AS ?type)
  }
}
ORDER BY ?id ?type ?value
