version = 1

[*]
threads = -1
flash-attn = on
mlock = off
mmap = off
fit = on
warmup = off
jinja = true
direct-io = on
batch-size = 2048
ubatch-size = 512
#ctx-size = 65536 # getting it from env LLAMA_ARG_CTX_SIZE
n-predict = 8192
n-gpu-layers = 99

# --- MODELS ---
[gpt-oss-120b]
hf = unsloth/gpt-oss-120b-GGUF:Q8_0
#hf = ggml-org/gpt-oss-120b-GGUF # tried this version provided by llama.cpp with MXFP4 quant
alias = gpt-oss-120b
#ot = .ffn_.*_exps.=CPU # offloads experts to CPU, is very GPU memory efficient, but slow
temp = 1.0
top-k = 0
top-p = 1.0
min-p = 0.0

[nemotron-3-super-120B-a12b]
hf = unsloth/NVIDIA-Nemotron-3-Super-120B-A12B-GGUF:UD-IQ4_NL
alias = nemotron-3-super-120B-a12b
temp = 0.6
top-p = 0.95

[gemma-4-31b]
hf = unsloth/gemma-4-31B-it-GGUF:UD-Q8_K_XL
alias = gemma-4-31b
n-gpu-layers = 99
temp = 1.0
top-p = 0.95
top-k = 64

[qwen-3.6-27b]
hf = unsloth/Qwen3.6-27B-GGUF:UD-Q8_K_XL
alias = qwen-3.6-27b
n-gpu-layers = 99
temp = 0.6
top-p = 0.95
top-k = 20
presence-penalty = 0.0
repeat-penalty = 1.0
