PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?id ?value ?type WHERE {
  # Get additional information, such as label, alias, comment, domain, range, type, and superclass
  {
    VALUES ?id { {IDS} }
    ?id rdfs:label ?value
    FILTER(LANG(?value) = "en")
    BIND("label" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id skos:altLabel ?value
    FILTER(LANG(?value) = "en")
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id rdfs:comment ?value
    FILTER(LANG(?value) = "en")
    BIND("other" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id rdfs:domain/rdfs:label ?domain
    FILTER(LANG(?domain) = "en")
    BIND(CONCAT("has domain ", ?domain) AS ?value)
    BIND("other" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id rdfs:range/rdfs:label ?range
    FILTER(LANG(?range) = "en")
    BIND(CONCAT("has range ", ?range) AS ?value)
    BIND("other" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id rdf:type/rdfs:label ?typ
    FILTER(LANG(?typ) = "en")
    BIND(CONCAT("is a ", ?typ) AS ?value)
    BIND("other" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id rdfs:subPropertyOf/rdfs:label ?superproperty
    FILTER(LANG(?superproperty) = "en")
    BIND(CONCAT("is subproperty of ", ?superproperty) AS ?value)
    BIND("other" AS ?type)
  }
} ORDER BY ?id ?type ?value
